Recom_Pharmacy/Models/HOADONNHAP.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recom_Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONNHAP()
        {
            this.CHITIETHDNs = new HashSet<CHITIETHDN>();
        }
    
        public int ID { get; set; }
        public string SOHD { get; set; }
        public int MATDV { get; set; }
        public Nullable<int> MAKHO { get; set; }
        public Nullable<int> MANCC { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public decimal TONGTIEN { get; set; }
        public string MALOAITIEN { get; set; }
        public double VAT { get; set; }
        public Nullable<int> TIENNO { get; set; }
        public string GHICHU { get; set; }
        public bool TRANGTHAI { get; set; }
    
        public virtual KHO KHO { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual TRINHDUOCVIEN TRINHDUOCVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDN> CHITIETHDNs { get; set; }
    }
}

Recom_Pharmacy/Models/HoaDonNhapViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Recom_Pharmacy.Models
{
    public class HoaDonNhapViewModel
    {
        public HOADONNHAP hoadonnhap  { get; set; }
        public List <ChiTietNhapViewModel>  chitiet { get; set; }
    }

    public class ChiTietNhapViewModel
    {
        public int ID { get; set; }
        public int MADVT { get; set; }
        public string TENTHUOC { get; set; }
        public decimal GIANHAP { get; set; }
        public decimal GIABAN { get; set; }
        public int SOLUONG { get; set; }
        public double THANHTIEN { get; set; }
        public DateTime NGAYSX { get; set; }
        public DateTime NGAYHH { get; set; }

        public string LOSX { get; set; }
        public string VITRI { get; set; }

        public bool TRANGTHAI { get; set; }


        public virtual DONVITINH DONVITINH { get; set; }
        public virtual HOADONNHAP HOADONNHAP { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}

Recom_Pharmacy/Controllers/HoaDonNhapController.cs
using PagedList;
using Recom_Pharmacy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Vonage.Common.Monads;
using System.Data.Entity;
using Filter = Recom_Pharmacy.Models.Common.Filter;
using Microsoft.Ajax.Utilities;
using Recom_Pharmacy.Models.Common;
using System.Web.Helpers;
using System.Data.Entity.Migrations;

namespace Recom_Pharmacy.Controllers
{
    public class HoaDonNhapController : Controller
    {
        private RecomPharmacyEntities db = new RecomPharmacyEntities();
        private tbl_SYS_SEQUENCE _sequence = new tbl_SYS_SEQUENCE();
        private SYS_SEQUENCE _seq = new SYS_SEQUENCE();

        // GET: HoaDonNhap  
        public ActionResult Index(string Searchtext, int? page, int? SelectedNV, int? SelectedNCC)
        {
            ViewBag.NhanVien = new SelectList(db.TRINHDUOCVIENs.ToList(), "ID", "TENNV");
            ViewBag.NCC = new SelectList(db.NCCs.ToList(), "ID", "TENNCC");
            var pageSize = 5;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<HOADONNHAP> items = db.HOADONNHAPs.OrderByDescending(x => x.ID);
            if (!string.IsNullOrEmpty(Searchtext))
            {
                string searchKeyword = Filter.ChuyenCoDauThanhKhongDau(Searchtext);
                items = items.Where(x => Filter.ChuyenCoDauThanhKhongDau(x.SOHD).StartsWith(searchKeyword, StringComparison.OrdinalIgnoreCase) ||
                                         Filter.ChuyenCoDauThanhKhongDau(x.SOHD).Contains(searchKeyword) ||
                                         x.SOHD.Contains(Searchtext));

            }
            if (SelectedNV.HasValue)
            {
                items = items.Where(x => x.TRINHDUOCVIEN.ID == SelectedNV.Value);
            }
            if (SelectedNCC.HasValue)
            {
                items = items.Where(x => x.NCC.ID == SelectedNCC.Value);
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.SelectedNV = SelectedNV;
            ViewBag.page = page;
            var ac = (Admin)Session["Account"];
            if (ac == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                return View(items);
            }
        }

        // GET: CTHDN/Create
        public ActionResult Add()
        {
            ViewBag.MATDV = new SelectList(db.TRINHDUOCVIENs, "ID", "TENNV");
            ViewBag.MANCC = new SelectList(db.NCCs, "ID", "TENNCC");
            ViewBag.MAKHO = new SelectList(db.KHOes, "ID", "TENKHO");
            _seq = _sequence.getItem(Constant.maphieunhap);
            if(_seq == null)
            {
                _seq.SEQNAME = Constant.maphieunhap;
                _seq.SEQVALUE = 1;
                _sequence.add(_seq);
                TempData["SOHD"] = _seq.SEQVALUE.Value.ToString("000000") + @"/" + DateTime.Today.Year.ToString().Substring(2, 2) + @"/NHH";
            }
            else
            {
            TempData["SOHD"] = (_seq.SEQVALUE + 1).Value.ToString("000000") + @"/" + DateTime.Today.Year.ToString().Substring(2, 2) + @"/NHH";
                }
            return View();
        }

        // POST: CTHDN/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateHeaderAntiForgeryToken]
        public ActionResult Add(HoaDonNhapViewModel hoadon)
        {
            if (hoadon != null)
            {
                try
                {
                    HOADONNHAP hdn = new HOADONNHAP();
                    hdn = hoadon.hoadonnhap;
                    db.HOADONNHAPs.Add(hdn);
                    foreach (var item in hoadon.chitiet)
                    {
                        var cTietTonKho = db.CTTONKHOes.FirstOrDefault(a => a.MATHUOC == item.ID && a.LOSX == item.LOSX);
                        if(cTietTonKho != null)
                        {
                            return Json(new { success = false,errMessage="Lô sản xuất đã tồn tại (" + cTietTonKho.LOSX +"), Ngày sx: (" + cTietTonKho.NGAYSX+")" });
                        }
                        CHITIETHDN chiTietHdn = new CHITIETHDN();
                        chiTietHdn.MAHDN = hdn.ID;
                        chiTietHdn.MATHUOC = item.ID;
                        chiTietHdn.SOLUONG = item.SOLUONG;
                        chiTietHdn.DONGIA = item.GIANHAP;
                        chiTietHdn.MADVT = item.MADVT;
                        chiTietHdn.LOSX = item.LOSX;
                        db.CHITIETHDNs.Add(chiTietHdn);
                        
                        CTTONKHO chiTietTonKho = new CTTONKHO();
                        chiTietTonKho.MAKHO = (int)hdn.MAKHO;
                        chiTietTonKho.DVT = item.MADVT;
                        chiTietTonKho.MATHUOC = item.ID;
                        chiTietTonKho.KE = item.VITRI;
                        chiTietTonKho.LOSX = item.LOSX;
                        chiTietTonKho.NGAYSX = item.NGAYSX;
                        chiTietTonKho.NGAYHH = item.NGAYHH;
                        chiTietTonKho.SLTON = item.SOLUONG;
                        chiTietTonKho.TRANGTHAI = true;
                        chiTietTonKho.GIANHAP = item.GIANHAP;
                        chiTietTonKho.GIABAN = item.GIABAN;
                        db.CTTONKHOes.Add(chiTietTonKho);
                    }

                    db.SaveChanges();
                    _seq = _sequence.getItem(Constant.maphieunhap);
                    if (_seq != null)
                    {
                        _seq.SEQNAME = Constant.maphieunhap;
                         _sequence.update(_seq);
                    }
                }
              catch(Exception ex)
                {
                    return Json(new { success = false,errMessage=ex.Message});
                }
                return Json(new { success = true,redirectURL="/hoadonnhap/index" });
            }
            return Json(new { success = false });
        }
        public ActionResult getAllThuoc(string searchTerm,int pageSize, int pageNum)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var key = (searchTerm?.ToLower().Trim()) ?? "";
            var thuoc = db.THUOCs.Where(p =>p.TENTHUOC.ToLower().Contains(key)).ToList();
            var result = new
            {
                Total = thuoc.Count(),
                thuoc = thuoc.Skip((pageNum * pageSize) - 5).Take(pageSize)
            };
            return new JsonResult
            {
                Data = result,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        [HttpGet]
        public JsonResult getDVTByIdThuoc(int id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var dvt = db.QUYDOIDVs
                .Where(q => q.MATHUOC == id)
                .Select(q => q.DONVITINH)
                .Distinct() // Đảm bảo không có bản ghi trùng lặp
                .ToList();
            return Json(new { success = true, dvtData = dvt}, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteAll(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if (items != null && items.Any())
                {
                    foreach (var item in items)
                    {
                        var id = Convert.ToInt32(item);
                        var obj = db.HOADONNHAPs.Include(i => i.CHITIETHDNs).FirstOrDefault(x => x.ID == id);
                        obj.TRANGTHAI = false;
                        foreach (CHITIETHDN chitiet in obj.CHITIETHDNs)
                        {
                            var tonkho = db.CTTONKHOes.FirstOrDefault(a=>a.LOSX == chitiet.LOSX && a.MATHUOC==chitiet.MATHUOC);
                            if (tonkho != null)
                            {
                                tonkho.TRANGTHAI = false;
                                db.CTTONKHOes.AddOrUpdate(tonkho);
                            }

                        }
                        db.SaveChanges();
                    }
                }
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

Recom_Pharmacy/Views/HoaDonNhap/Index.cshtml
@model PagedList.PagedList<Recom_Pharmacy.Models.HOADONNHAP>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản lý Hóa đơn nhập</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/admin/index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-lg-5">
                    <div class="card-tools">
                        <a href="/hoadonnhap/add" class="btn btn-primary">Thêm mới</a>
                        <a href="#" class="btn btn-danger" id="btnDeleteAll">Xóa</a>
                    </div>
                </div>
            </div>

        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    @using (Html.BeginForm("index", "HoaDonNhap", FormMethod.Get, new { }))
                    {
                        <div class="input-group input-group-sm">
                            @Html.TextBox("Searchtext", null, new { @class = "form-control" })
                            <span class="input-group-append">
                                <button type="submit" class="btn btn-info btn-flat">Tìm kiếm</button>
                            </span>
                        </div>
                    }
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover display" style="width: 100%;color:black;">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="SelectAll" /></th>
                            <th>STT</th>
                            <th>Số hóa đơn</th>
                            <th>Nhân viên lập</th>
                            <th>Nhà cung cấp</th>
                            <th>Ngày nhập</th>
                            <th>Tổng tiền</th>
                            <th>Loại tiền</th>
                            <th>VAT</th>
                            <th>Tiền nợ</th>
                            <th>Ghi chú</th>
                            <th>Trạng thái</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Any())
                        {
                            var i = ((ViewBag.page - 1) * ViewBag.PageSize) + 1;
                            foreach (var item in Model)
                            {
                                <tr id="trow_@item.ID">
                                    <td><input type="checkbox" class="cbkItem" value="@item.ID" /></td>
                                    <td>@i</td>
                                    <td>@item.SOHD</td>
                                    <td>@item.TRINHDUOCVIEN.TENNV</td>
                                    <td>@(item.NCC?.TENNCC ?? "N/A")</td>
                                    <td>@item.NGAYNHAP</td>
                                    <td>@item.TONGTIEN</td>
                                    <td>@item.MALOAITIEN</td>
                                    <td>@item.VAT</td>
                                    <td>@item.TIENNO</td>
                                    <td>@item.GHICHU</td>
                                    <td>@item.TRANGTHAI</td>
                                    <td>
                                        <a href="/cthdn/index/@item.ID" class="btn btn-sm btn-primary">Chi tiết HĐN</a>
                                        @*<a href="#" data-id="@item.ID" class="btn btn-sm btn-danger btnDelete">Xóa</a>*@
                                    </td>
                                </tr>
                                i++;
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="4">Không có bản ghi nào!</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col-6"></div>
                <div class="col-6" style="text-align:right">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>
            </div>
        </div>

        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>

@section scripts{
    <script>
        $(document).ready(function myfunction() {
            $('body').on('click', '#btnDeleteAll', function (e) {
                e.preventDefault();
                var str = "";
                var checkbox = $(this).parents('.card').find('tr td input:checkbox')
                var i = 0;
                checkbox.each(function () {
                    if (this.checked) {
                        checkbox.attr('selected', 'checked')
                        var _id = $(this).val();
                        if (i === 0) {
                            str += _id;
                        } else {
                            str += "," + _id;
                        }
                        i++;
                    } else {
                        checkbox.attr('selected', '')
                    }
                });
                if (str.length > 0) {
                    var conf = confirm('Bạn có muốn xóa các bản ghi này hay không?');
                    if (conf === true) {
                        $.ajax({
                            url: '/hoadonnhap/deleteAll',
                            type: 'POST',
                            data: { ids: str },
                            success: function (rs) {
                                if (rs.success) {
                                    location.reload();
                                }
                            }
                        });
                    }
                }
            });

            $('body').on('change', '#SelectAll', function () {
                var checkStatus = this.checked;
                var checkbox = $(this).parents('.card-body').find('tr td input:checkbox');
                checkbox.each(function () {
                    this.checked = checkStatus;
                    if (this.checked) {
                        checkbox.attr('selected', 'checked');
                    } else {
                        checkbox.attr('selected', '');
                    }
                });
            });


            $('body').on('click', '.btnDelete', function myfunction() {
                var id = $(this).data("id");
                var conf = confirm('Bạn có muốn xóa  bản ghi này không?')
                if (conf == true) {
                    $.ajax({
                        url: '/hoadonnhap/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();

                            }
                        }
                    });
                }
            });
        });


    </script>
}