Recom_Pharmacy/Models/TINHTHANH.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recom_Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTHANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TINHTHANH()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
            this.TRINHDUOCVIENs = new HashSet<TRINHDUOCVIEN>();
        }
    
        public int ID { get; set; }
        public string TENTINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRINHDUOCVIEN> TRINHDUOCVIENs { get; set; }
    }
}

Recom_Pharmacy/Controllers/TinhThanhController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Recom_Pharmacy.Models;
using PagedList;
using Filter = Recom_Pharmacy.Models.Common.Filter;
using System.Web.UI;

namespace Recom_Pharmacy.Controllers
{
    public class TinhThanhController : Controller
    {
        private RecomPharmacyEntities db = new RecomPharmacyEntities();

        // GET: TinhThanh
        public ActionResult Index(string Searchtext, int? page)
        {
            var pageSize = 15;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<TINHTHANH> items = db.TINHTHANHs.OrderByDescending(x => x.ID);
            if (!string.IsNullOrEmpty(Searchtext))
            {
                string searchKeyword = Filter.ChuyenCoDauThanhKhongDau(Searchtext);
                items = items.Where(x => Filter.ChuyenCoDauThanhKhongDau(x.TENTINH).StartsWith(searchKeyword, StringComparison.OrdinalIgnoreCase) ||
                                         Filter.ChuyenCoDauThanhKhongDau(x.TENTINH).Contains(searchKeyword) ||
                                         x.TENTINH.Contains(Searchtext));

            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.page = page;
            var ac = (Admin)Session["Account"];
            if (ac == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                return View(items);
            }
        }

        // GET: TinhThanh/Create
        public ActionResult Add()
        {
            return View();
        }

        // POST: TinhThanh/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "ID,TENTINH")] TINHTHANH tINHTHANH)
        {
            if (ModelState.IsValid)
            {
                db.TINHTHANHs.Add(tINHTHANH);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tINHTHANH);
        }

        // GET: TinhThanh/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TINHTHANH tINHTHANH = db.TINHTHANHs.Find(id);
            if (tINHTHANH == null)
            {
                return HttpNotFound();
            }
            return View(tINHTHANH);
        }

        // POST: TinhThanh/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TENTINH")] TINHTHANH tINHTHANH)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tINHTHANH).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tINHTHANH);
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = db.TINHTHANHs.Find(id);
            if (item != null)
            {
                db.TINHTHANHs.Remove(item);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

        [HttpPost]
        public ActionResult DeleteAll(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if (items != null && items.Any())
                {
                    foreach (var item in items)
                    {
                        var obj = db.TINHTHANHs.Find(Convert.ToInt32(item));
                        db.TINHTHANHs.Remove(obj);
                        db.SaveChanges();
                    }
                }
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

Recom_Pharmacy/Views/TinhThanh/Add.cshtml
@model Recom_Pharmacy.Models.TINHTHANH

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm mới Tỉnh thành</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Tỉnh Thành</a></li>
                    <li class="breadcrumb-item active">Thêm mới</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <div class="card-body">
        <div class="bs-stepper-content">
            @using (Html.BeginForm("Add", "TinhThanh", FormMethod.Post, new { }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <!-- your steps content here -->
                <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tên tỉnh</label>
                        @Html.TextBoxFor(x => x.TENTINH, new { @class = "form-control", @placeholder = "Nhập vào tên tỉnh" })
                        @Html.ValidationMessageFor(x => x.TENTINH, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <a href="/tinhthanh" class="btn btn-danger">Quay lại</a>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>

            }
        </div>
    </div>

</section>

<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>

Recom_Pharmacy/Views/TinhThanh/Edit.cshtml
@model Recom_Pharmacy.Models.TINHTHANH

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cập nhật tỉnh thành</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/tinhthanh">Tỉnh thành</a></li>
                    <li class="breadcrumb-item active">Cập nhật</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="card-body">
        @if (Model != null)
        {
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Edit", "TinhThanh", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(x => x.ID)
                    <!-- your steps content here -->
                    <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Tên Tỉnh thành</label>
                            @Html.TextBoxFor(x => x.TENTINH, new { @class = "form-control", @placeholder = "Nhập tên tỉnh thành cần chỉnh sửa" })
                            @Html.ValidationMessageFor(x => x.TENTINH, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <a href="/tinhthanh" class="btn btn-danger">Quay lại</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                }
            </div>
        }
    </div>
    <!-- /.card-body -->
    <!-- /.card -->

</section>

Recom_Pharmacy/Views/TinhThanh/Index.cshtml
@model PagedList.PagedList<Recom_Pharmacy.Models.TINHTHANH>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản lý Tỉnh thành</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/admin/index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <div class="card-tools">
                <a href="/tinhthanh/add" class="btn btn-primary">Thêm mới</a>
                <a href="#" class="btn btn-danger" id="btnDeleteAll">Xóa</a>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    @using (Html.BeginForm("index", "TinhThanh", FormMethod.Get, new { }))
                    {
                        <div class="input-group input-group-sm">
                            @Html.TextBox("Searchtext", null, new { @class = "form-control" })
                            @*<input type="text" name="searchtext" class="form-control">*@
                            <span class="input-group-append">
                                <button type="submit" class="btn btn-info btn-flat">Tìm kiếm</button>
                            </span>
                        </div>
                    }
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover display" style="width: 100%;color:black;">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="SelectAll" /></th>
                            <th>STT</th>
                            <th>Tên tỉnh thành</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Any())
                        {
                            var i = ((ViewBag.page - 1) * ViewBag.PageSize) + 1;
                            foreach (var item in Model)
                            {
                                <tr id="trow_@item.ID">
                                    <td><input type="checkbox" class="cbkItem" value="@item.ID" /></td>
                                    <td>@i</td>
                                    <td>@item.TENTINH</td>
                                    <td>
                                        <a href="/tinhthanh/edit/@item.ID" class="btn btn-sm btn-primary">Sửa</a>
                                        <a href="#" data-id="@item.ID" class="btn btn-sm btn-danger btnDelete">Xóa</a>
                                    </td>
                                </tr>
                                i++;
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="4">Không có bản ghi nào!</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col-6"></div>
                <div class="col-6" style="text-align:right">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>
            </div>
        </div>

        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>

@section scripts{
    <script>
        $(document).ready(function myfunction() {
            $('body').on('click', '#btnDeleteAll', function (e) {
                e.preventDefault();
                var str = "";
                var checkbox = $(this).parents('.card').find('tr td input:checkbox')
                var i = 0;
                checkbox.each(function () {
                    if (this.checked) {
                        checkbox.attr('selected', 'checked')
                        var _id = $(this).val();
                        if (i === 0) {
                            str += _id;
                        } else {
                            str += "," + _id;
                        }
                        i++;
                    } else {
                        checkbox.attr('selected', '')
                    }
                });
                if (str.length > 0) {
                    var conf = confirm('Bạn có muốn xóa các bản ghi này hay không?');
                    if (conf === true) {
                        $.ajax({
                            url: '/tinhthanh/deleteAll',
                            type: 'POST',
                            data: { ids: str },
                            success: function (rs) {
                                if (rs.success) {
                                    location.reload();
                                }
                            }
                        });
                    }
                }
            });

            $('body').on('change', '#SelectAll', function () {
                var checkStatus = this.checked;
                var checkbox = $(this).parents('.card-body').find('tr td input:checkbox');
                checkbox.each(function () {
                    this.checked = checkStatus;
                    if (this.checked) {
                        checkbox.attr('selected', 'checked');
                    } else {
                        checkbox.attr('selected', '');
                    }
                });
            });


            $('body').on('click', '.btnDelete', function myfunction() {
                var id = $(this).data("id");
                var conf = confirm('Bạn có muốn xóa  bản ghi này không?')
                if (conf == true) {
                    $.ajax({
                        url: '/tinhthanh/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();

                            }
                        }
                    });
                }
            });

            $('body').on('click', '.btnActive', function (e) {
                e.preventDefault();
                var btn = $(this);
                var id = btn.data("id");
                $.ajax({
                    url: '/tinhthanh/IsActive',
                    type: 'POST',
                    data: { id: id },
                    success: function (rs) {
                        if (rs.success) {
                            if (rs.isAcive) {
                                btn.html("<i class='fa fa-check text-success'></i>");
                            } else {
                                btn.html("<i class='fas fa-times text-danger'></i>");
                            }
                        }

                    }
                });
            });
        });


    </script>
}